version: "3.9"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./BackEnd
    ports:
      - "5000:5000"
    volumes:
      - ./BackEnd:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  frontend:
    build: ./UI
    ports:
      - "3000:3000"
    volumes:
      - ./UI:/app
    environment:
      - BACKEND_URI=http://backend:5000/
    depends_on:
      - backend

volumes:
  mongo_data:
